CREATE DATABASE AIRPORTS

use AIRPORTS

CREATE TABLE LOCATIONS (
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    CITY NVARCHAR(255) NULL,
    COUNTRY NVARCHAR(255) NULL,
    CODE NVARCHAR(50) NULL,
    CONTINENT NVARCHAR(255) NULL
);

SELECT * FROM Locations

DROP TABLE LOCATIONS

